/*INSERT TABELA CATEGORIA
 * id_categoria INT PRIMARY KEY,
	tipo VARCHAR2(20),
 * */
INSERT INTO CATEGORIA VALUES(1, 'MOUSE');



/*INSERT TABELA FORNECEDOR
 * id_fornecedor INT PRIMARY KEY,
	nome VARCHAR2(50) NOT NULL,
	cnpj VARCHAR2(14) NOT NULL UNIQUE,
	telefone VARCHAR2(9)
 * */

INSERT INTO FORNECEDOR VALUES (1,'JAMILTON','19192319321925','999999999');



/*INSERT TABELA PRODUTO
 * id_produto INT PRIMARY KEY,
	id_categoria INT,
	id_fornecedor INT,
	nome VARCHAR2(50) NOT NULL,
	descricao VARCHAR2(30) NOT NULL,
	preco_unitario DECIMAL(10,2) NOT NULL,
	quantidade_minima INT NOT NULL,*/
INSERT INTO PRODUTO VALUES (1,1,1, 'REDRAGON', 'rato', 150.00, 5);






/*INSERT TABELA 
 * */


